_BASE_: "../Base-WithCenter.yml"

MODEL:
  BACKBONE:
    WITH_IBN: True

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  DO_AUTOAUG: True

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/market1501/sbs_R50-ibn_center"